project:
  type: book
  output-dir: ./docs

book:
  title: "Title of the thesis"
  author:
    - name: Aida Farahani 
      email: aida.farahani@informatik.tu-chemnitz.de
      url: https://hex41434.github.io/
      affiliation: Chemnitz University of Technology
      affiliation-url: https://tu-chemnitz.de
      orcid: 0000-0000-0000-0000
  date: "2024"
  date-format: "YYYY"

  
  chapters:
    - index.qmd
    - 1-Introduction.qmd
    - 2-StateOfTheArt.qmd
    - 3-Methods.qmd
    - 4-Results.qmd
    - 5-Discussion.qmd
    - References.qmd

  output-file: "thesis"

  sidebar:
    logo: img/tuc.png
    style: "docked"
    background: white

  downloads:
    - pdf

# Bibliography
bibliography: references.bib
csl: assets/frontiers.csl
number-sections: true
highlight-style: github

format:
  html:
    theme: ['sandstone', assets/custom.scss]
    page-layout: full
    smooth-scroll: true
    html-math-method: katex
    page-navigation: true

  pdf:
    documentclass: scrbook
    keep-tex: true

    # Table of contents
    toc: true
    toc-depth: 3
    toc-title: "Table of contents"
    lof: false
    lot: false

    # Fonts
    mainfont: "Roboto"
    monofont: "Inconsolata"
    fontsize: 11pt

    # Setup
    geometry: 
      - margin=1in
      - heightrounded
    papersize: a4
    linestretch: 1.25
    colorlinks: true
    linkcolor: ForestGreen

    # Title page
    template-partials:
      - assets/before-body.tex
    logo: img/tuc.png
    info:
        - Geboren am 03.05.1985 in Tehran (Iran)
    genre-text: "Dissertation zur Erlangung des akademischen Grades"
    genre: "PhD"
    lab: Professur für künstliche Intelligenz
    department: Fakultät für Informatik 
    university: Technische Universität Chemnitz


# See https://cameronpatrick.com/post/2023/07/quarto-thesis-formatting/
